ボウリングのスコア計算プログラムオブジェクト指向版
maeda-m/ruby-practices pull request #11
Opened 2022-08-11 12:18 UTC by maeda-m

## 必須要件

- [ ] ボウリングのスコア計算プログラムをオブジェクト指向で書いてPull RequestとしてアップしてそのURLとTerminalでの実行結果を提出しよう。
- [ ] rubocop-fjordの実行結果も一緒に載せること。
- [ ] Pull Request はForkした自分自身のリポジトリに対して作成しよう。

## 関連PR

- #3

## 修正時チェックリスト

- [ ] [セルフレビューを考える](https://www.maeda-m.com/2022/04/10/self-review-recomend.html) は読みましたか👀
- [ ] [すばやく確認OKをもらうためのセルフレビュー - よもやま話β版](https://beta-chelsea.hatenadiary.jp/entry/2020/12/19/125756) は読みましたか👀
- [ ] レビューコメントで他に適用可能なものがあるか確認し、対応方針と結果をコメントしましたか🚓

2022-08-23 16:00 UTC, u1tnk requested changes
もうちょっとシンプルな構造にしましょう。詳細は該当部分にコメントしてあります。

2022-08-23 16:00 UTC, u1tnk commented on 07.bowling_object/bowling/frame.rb
> +    def self.create_transfers(values)
transferも無くしてframeだけにしちゃいましょう！
reverse_eachしてるのはnext_frameを入れたいからと思うのですが、indexを保持してるのでnext_frameをinitializeから以外で摂る方法もあると思いますし。valuesとindexからどうにかする方法もありますね。


ちにみに bonus_pointは一個ずつfrmae見てますが、record_valuesを保持すれば単に次の次まで取れば良いので、next_frame取れるようにしても良いですし、

2022-08-24 14:30 UTC, u1tnk requested changes
だいぶ読みやすくなりました！

ただ、もうちょっとバランスが良くないと思いました。

- Shotに strikeやspareがあるのは違和感がある。
- Gameに処理が集中していてframeに処理がほぼ無くバランスが悪い。

一部のクラスに責務が偏らず、各クラスにあるべき処理を担う(どっちか悩むような機能はあると思いますが)重要と思うのでもう少し見直して欲しいと思います 🙏

2022-09-14 12:29 UTC, u1tnk requested changes
大体大丈夫なのですが細かいところをいくつかコメントしました！

2022-09-14 12:29 UTC, u1tnk commented on 07.bowling_object/bowling/game.rb
> +    def final_frame?(position)
この処理は indexを Frameに持たせるようにして Frameで判断した方がスッキリすると思います。

2022-09-14 12:29 UTC, u1tnk commented on 07.bowling_object/bowling/shot.rb
> +    # See: https://docs.ruby-lang.org/ja/latest/method/Numeric/i/coerce.html
このメソッドと `==` を定義しているのはどういう意図でしょうか？

2022-09-14 14:10 UTC, maeda-m reviewed
`Game#final_frame?(position)` の対応方針と `Shot#coerce` 、`Shot#==` の意図を記載しました🙏

2022-09-14 14:10 UTC, maeda-m commented on 07.bowling_object/bowling/shot.rb
> +    # See: https://docs.ruby-lang.org/ja/latest/method/Numeric/i/coerce.html
`coerce` は `sum` などでわざわざ `shot.to_i` をしなくても良いようにするために定義しています（数値クラスの算術演算子で自身を変換するため）。

`==` は `Shot` のオブジェクトを `@shots.find_index` で比較しているケースと `@shots.first == MAX_HIT_COUNT` などで `Integer` のオブジェクトと比較しているケースで、それぞれ値っぽく振る舞うために定義しています。

2022-09-14 14:10 UTC, maeda-m commented on 07.bowling_object/bowling/game.rb
> +    def final_frame?(position)
そうですよねー。
`Frame` クラスに `FINAL_FRAME_POSITION` などといった定数を追加して `Frame` で判断させるようにします。

2022-09-14 16:23 UTC, u1tnk commented on 07.bowling_object/bowling/shot.rb
> +    # See: https://docs.ruby-lang.org/ja/latest/method/Numeric/i/coerce.html
なるほど。了解しました！

2022-09-14 16:24 UTC, u1tnk approved these changes
OKです 🙆‍♀️

2022-09-14 22:49 UTC, merged

2022-09-14 22:50 UTC, maeda-m commented
マージしました🎉